<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>mp02</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="mp02_files/libs/clipboard/clipboard.min.js"></script>
<script src="mp02_files/libs/quarto-html/quarto.js"></script>
<script src="mp02_files/libs/quarto-html/popper.min.js"></script>
<script src="mp02_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="mp02_files/libs/quarto-html/anchor.min.js"></script>
<link href="mp02_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="mp02_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="mp02_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="mp02_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="mp02_files/libs/bootstrap/bootstrap-3119dc400b02922c27171a4b76b1a7ff.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="mp02_files/libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
<script src="mp02_files/libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="mp02_files/libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="mp02_files/libs/datatables-binding-0.33/datatables.js"></script>
<script src="mp02_files/libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="mp02_files/libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="mp02_files/libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="mp02_files/libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="mp02_files/libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">
<script src="mp02_files/libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>


<link rel="stylesheet" href="css/styles.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#the-eia-electricity-report" id="toc-the-eia-electricity-report" class="nav-link active" data-scroll-target="#the-eia-electricity-report">The EIA Electricity Report</a>
  <ul class="collapse">
  <li><a href="#task-1-data-importation" id="toc-task-1-data-importation" class="nav-link" data-scroll-target="#task-1-data-importation">Task 1: Data Importation</a></li>
  <li><a href="#task-2-initial-analysis-of-sep-data" id="toc-task-2-initial-analysis-of-sep-data" class="nav-link" data-scroll-target="#task-2-initial-analysis-of-sep-data">Task 2: Initial Analysis of SEP Data</a></li>
  <li><a href="#energy-consumption-by-u.s.-transit-agencies" id="toc-energy-consumption-by-u.s.-transit-agencies" class="nav-link" data-scroll-target="#energy-consumption-by-u.s.-transit-agencies">Energy Consumption by U.S. Transit Agencies</a></li>
  <li><a href="#task-3-recording-the-mode-column" id="toc-task-3-recording-the-mode-column" class="nav-link" data-scroll-target="#task-3-recording-the-mode-column">Task 3: Recording the Mode Column</a></li>
  <li><a href="#task-4-explore-ntd-service-data" id="toc-task-4-explore-ntd-service-data" class="nav-link" data-scroll-target="#task-4-explore-ntd-service-data">Task 4: Explore NTD Service Data</a></li>
  <li><a href="#task-5-calculate-emissions" id="toc-task-5-calculate-emissions" class="nav-link" data-scroll-target="#task-5-calculate-emissions">Task 5: Calculate Emissions</a></li>
  <li><a href="#task-6-normalize-emissions-to-transit-usage" id="toc-task-6-normalize-emissions-to-transit-usage" class="nav-link" data-scroll-target="#task-6-normalize-emissions-to-transit-usage">Task 6: Normalize Emissions to Transit Usage</a></li>
  <li><a href="#task-7-determine-award-winners" id="toc-task-7-determine-award-winners" class="nav-link" data-scroll-target="#task-7-determine-award-winners">Task 7: Determine Award Winners</a></li>
  <li><a href="#task-8-visualization" id="toc-task-8-visualization" class="nav-link" data-scroll-target="#task-8-visualization">Task 8: Visualization</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">




<section id="the-eia-electricity-report" class="level1">
<h1>The EIA Electricity Report</h1>
<section id="task-1-data-importation" class="level2">
<h2 class="anchored" data-anchor-id="task-1-data-importation">Task 1: Data Importation</h2>
<p>The following report is a table that contains information about the electricity industry in different U.S. states.</p>
<ul>
<li><strong>Pounds of CO2 emitted per MWh of electricity produced</strong></li>
<li><strong>The dominant type of electricity generation source in each state.</strong></li>
<li><strong>The average retail price of electricity for 1000 kWh in dollars.</strong></li>
<li><strong>The total electricity generation capacity in megawatt-hours. </strong></li>
</ul>
<p>This is to ensure that all the data has been imported correctly as represented by this table.</p>
<div class="cell">
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-9aaef613cb531df1d695" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-9aaef613cb531df1d695">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50"],["1,925","1,864","1,741","1,514","1,497","1,444","1,414","1,354","1,180","1,148","1,127","1,103","1,095","1,054","1,044","987","966","923","912","855","847","817","801","794","775","763","759","733","727","715","684","655","654","648","639","594","576","558","558","522","522","518","440","428","370","369","344","292","269","8"],["Coal","Coal","Coal","Coal","Coal","Petroleum","Coal","Coal","Natural gas","Natural gas","Coal","Coal","Natural gas","Coal","Natural gas","Natural gas","Natural gas","Natural gas","Natural gas","Natural gas","Natural gas","Natural gas","Wind","Natural gas","Wind","Wind","Wind","Natural gas","Natural gas","Nuclear","Natural gas","Natural gas","Natural gas","Natural gas","Natural gas","Natural gas","Natural gas","Natural gas","Nuclear","Nuclear","Natural gas","Natural gas","Natural gas","Natural gas","Hydroelectric","Wind","Hydroelectric","Hydroelectric","Nuclear","Hydroelectric"],["$102.60","$83.90","$99.60","$108.70","$114.90","$386.00","$80.30","$90.30","$214.10","$127.20","$109.70","$91.40","$128.50","$117.60","$110.40","$97.30","$89.10","$232.10","$136.80","$100.40","$216.20","$109.50","$122.10","$135.30","$94.20","$108.00","$94.70","$110.60","$114.70","$106.90","$121.90","$125.70","$130.90","$93.00","$106.10","$106.80","$242.40","$143.40","$105.00","$117.50","$182.80","$152.70","$248.70","$208.40","$90.80","$104.90","$103.20","$95.80","$229.60","$175.30"],["52,286,784","43,181,420","63,217,080","66,703,285","90,046,880","9,194,164","42,068,807","33,496,554","6,717,825","62,548,705","26,895,758","39,445,955","4,772,059","57,541,720","133,223,464","63,195,647","97,784,565","19,695,884","120,656,625","547,294,552","10,430,846","72,933,440","57,276,862","259,798,479","69,836,973","58,456,598","39,269,073","129,221,513","139,435,010","77,791,204","111,838,736","235,924,937","42,164,375","89,236,024","126,553,394","91,059,344","40,666,418","36,000,650","100,853,387","177,737,641","124,039,988","64,228,924","216,628,794","12,512,181","17,842,446","17,436,158","61,691,869","102,960,605","16,824,999","2,480,199"],["West Virginia","Wyoming","Kentucky","Missouri","Indiana","Hawaii","North Dakota","Utah","Alaska","Wisconsin","Montana","Nebraska","Delaware","Colorado","Ohio","Arkansas","Louisiana","Massachusetts","Michigan","Texas","Rhode Island","Mississippi","Minnesota","Florida","Iowa","Kansas","New Mexico","Georgia","Alabama","Tennessee","Arizona","Pennsylvania","Nevada","Oklahoma","North Carolina","Virginia","Connecticut","Maryland","South Carolina","Illinois","New York","New Jersey","California","Maine","Idaho","South Dakota","Oregon","Washington","New Hampshire","Vermont"]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>Pounds of CO2 Emitted per MWh of Electricity Produced<\/th>\n      <th>Primary Source of Electricity Generation<\/th>\n      <th>Average Retail Price for 1000 kWh<\/th>\n      <th>Total Generation Capacity (MWh)<\/th>\n      <th>State<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"Pounds of CO2 Emitted per MWh of Electricity Produced","targets":1},{"name":"Primary Source of Electricity Generation","targets":2},{"name":"Average Retail Price for 1000 kWh","targets":3},{"name":"Total Generation Capacity (MWh)","targets":4},{"name":"State","targets":5}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>As we can see, since our table has redered the appropriate information, we can conclude that the data has been properly imported and can now begin our analysis.</p>
</section>
<section id="task-2-initial-analysis-of-sep-data" class="level2">
<h2 class="anchored" data-anchor-id="task-2-initial-analysis-of-sep-data">Task 2: Initial Analysis of SEP Data</h2>
<p><strong>Our first objective is to find which state has the most expensive retail electricity:</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>State with the most expensive retail electricity:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   state electricity_price_MWh
1 Hawaii                   386</code></pre>
</div>
</div>
<p><strong>Our next objective is to find the state with the “dirtiest” electricty mix, aka the state with the highest CO2 emissions:</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>State with the 'dirtiest' electricity mix (highest CO2 emissions per MWh):</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>          state CO2_MWh
1 West Virginia    1925</code></pre>
</div>
</div>
<p><strong>Now we will find on average, how many pounds of CO2 are emitted per MWh of electricity produced in the US:</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>The average CO2 emitted per MWh of electricity produced in the US is: 805.37 pounds.</code></pre>
</div>
</div>
<p><strong>Next, we want to find what is the rarest primary energy source in the US and what is the associated cost of electricity and where is it used:</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>The rarest primary energy source in the U.S. is: Petroleum </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>The associated cost of electricity is: 386 per MWh.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>States using this energy source are:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   state
1 Hawaii</code></pre>
</div>
</div>
<p><strong>Finally, we want to know how many times cleaner is NY’s energy mix than that of Texas:</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>New York's energy mix is 1.64 times cleaner than Texas's.</code></pre>
</div>
</div>
</section>
<section id="energy-consumption-by-u.s.-transit-agencies" class="level2">
<h2 class="anchored" data-anchor-id="energy-consumption-by-u.s.-transit-agencies">Energy Consumption by U.S. Transit Agencies</h2>
<p>The following table shows the energy consumption of various transit agencies in the U.S. in 2023. It illustrates how many agencies which use different kinds of transport (such as buses, subways and ferries) used each kind of fuel. Here is a quick overview of what the table shows:</p>
<ol type="1">
<li><strong>NTD ID:</strong> This is a unique identification of each transit agency or system.</li>
<li><strong>Mode:</strong> The kind of transport employed (for instance, bus, subway, etc.).</li>
<li><strong>Agency Name:</strong> The name of the transit agency.</li>
<li><strong>Fuel Types:</strong> The columns for different fuel types show the amount of energy consumed by each agency in that fuel type. For instance, Bio-Diesel and Electric Battery indicate the energy derived from these sources in gallons for non-electric fuels and kWh for electric sources.</li>
</ol>
<p>The data is cleaned and summarized to help us understand the energy impact of public transportation in the United States.</p>
<p>We’ve shown 10 random rows here to help you get a idea of how the energy consumption is split across different agencies and types of transport.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 16
   `NTD ID` Mode  `Agency Name`       `Bio-Diesel` `Bunker Fuel` `C Natural Gas`
      &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;                      &lt;dbl&gt;         &lt;dbl&gt;           &lt;dbl&gt;
 1    60114 MB    STAR Transit                   0             0               0
 2    90196 VP    County of Placer               0             0               0
 3    90311 VP    Stanislaus Council…            0             0               0
 4    60056 DR    Dallas Area Rapid …            0             0             100
 5    90012 DR    San Joaquin Region…            0             0               0
 6    50145 DR    City of Kokomo                 0             0               0
 7    70014 MB    Topeka Metropolita…            0             0               0
 8    60017 MB    Central Oklahoma T…            0             0          594146
 9        7 DR    Lane Transit Distr…            0             0               0
10    55312 SR    City of Milwaukee              0             0               0
# ℹ 10 more variables: `Diesel Fuel` &lt;dbl&gt;, `Electric Battery` &lt;dbl&gt;,
#   `Electric Propulsion` &lt;dbl&gt;, Ethanol &lt;dbl&gt;, Methonal &lt;dbl&gt;, Gasoline &lt;dbl&gt;,
#   Hydrogen &lt;dbl&gt;, Kerosene &lt;dbl&gt;, `Liquified Nat Gas` &lt;dbl&gt;,
#   `Liquified Petroleum Gas` &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="task-3-recording-the-mode-column" class="level2">
<h2 class="anchored" data-anchor-id="task-3-recording-the-mode-column">Task 3: Recording the Mode Column</h2>
<p>To begin with, we use the <code>distinct()</code> function to identify the distinct mode codes in the dataset from the <strong>Mode</strong> column. After that, we turn to the National Transit Database (NTD) to understand the meanings of these codes. Hence, we transform the <strong>Mode</strong> column to more understandable transportation types. Here is the code for the modified version that also includes the recoding of the <strong>Mode</strong> column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>NTD_ENERGY <span class="ot">&lt;-</span> NTD_ENERGY <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Mode =</span> <span class="fu">case_when</span>(</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    Mode <span class="sc">==</span> <span class="st">"HR"</span> <span class="sc">~</span> <span class="st">"Heavy Rail"</span>, </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    Mode <span class="sc">==</span> <span class="st">"LR"</span> <span class="sc">~</span> <span class="st">"Light Rail"</span>, </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    Mode <span class="sc">==</span> <span class="st">"MB"</span> <span class="sc">~</span> <span class="st">"Motor Bus"</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    Mode <span class="sc">==</span> <span class="st">"VP"</span> <span class="sc">~</span> <span class="st">"Van Pool"</span>, </span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    Mode <span class="sc">==</span> <span class="st">"TB"</span> <span class="sc">~</span> <span class="st">"Trolley Bus"</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    Mode <span class="sc">==</span> <span class="st">"SR"</span> <span class="sc">~</span> <span class="st">"Streetcar"</span>,</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    Mode <span class="sc">==</span> <span class="st">"DR"</span> <span class="sc">~</span> <span class="st">"Demand Response"</span>,</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    Mode <span class="sc">==</span> <span class="st">"FB"</span> <span class="sc">~</span> <span class="st">"Ferryboat"</span>,</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    Mode <span class="sc">==</span> <span class="st">"OB"</span> <span class="sc">~</span> <span class="st">"Automobile Bus"</span>,</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    Mode <span class="sc">==</span> <span class="st">"CB"</span> <span class="sc">~</span> <span class="st">"Commuter Bus"</span>,</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    Mode <span class="sc">==</span> <span class="st">"AB"</span> <span class="sc">~</span> <span class="st">"Arterial Bus"</span>,</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    Mode <span class="sc">==</span> <span class="st">"BT"</span> <span class="sc">~</span> <span class="st">"Bus Rapid Transit"</span>,</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Unknown"</span>  </span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>  ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-4-explore-ntd-service-data" class="level2">
<h2 class="anchored" data-anchor-id="task-4-explore-ntd-service-data">Task 4: Explore NTD Service Data</h2>
<p>Using the NTD_Service Data, we are able to solve for the following questions:</p>
<p><strong>Which transit service has the most UPT annually?</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>The transit service with the most UPT annually is: MTA New York City Transit with 2632003044 UPT.</code></pre>
</div>
</div>
<p><strong>What is the average trip length of a trip on MTA NYC?</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>The average trip length for MTA NYC is: 14.81 miles.</code></pre>
</div>
</div>
<p><strong>Which transit service in NYC has the longest average trip length?</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>The transit service in NYC with the longest average trip length is: MTA Long Island Rail Road with an average trip length of 24.26 miles.</code></pre>
</div>
</div>
<p><strong>Which state has the fewest total miles travelled by public transit?</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>The state with the fewest total miles travelled by public transit is: NH with 3749892 miles.</code></pre>
</div>
</div>
<p><strong>Are all states represented in this data?</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Some states are missing: Missing states include: AZ, AR, CA, CO, HI, IA, KS, LA, MO, MT, NE, NV, NM, ND, OK, SD, TX, UT, WY .</code></pre>
</div>
</div>
</section>
<section id="task-5-calculate-emissions" class="level2">
<h2 class="anchored" data-anchor-id="task-5-calculate-emissions">Task 5: Calculate Emissions</h2>
<p>This task requires merging NTD_SERVICE, NTD_ENERGY and EIA_SEP_REPORT datasets to determine CO2 emissions from public transit services. The data will be merged to generate a table with one row for each Agency + Mode Pair that includes state of operation, fuel sources used and CO2 emissions per MWh from the EIA_SEP_REPORT table. We will use this data to calculate the total CO2 emissions using the correct formula.</p>
<p>The process includes:</p>
<ul>
<li><p><strong>Merging the dataset to achieve data alignment.</strong></p></li>
<li><p><strong>Converting the NTD fuel names into EIA format.</strong></p></li>
<li><p><strong>The emissions calculation requires energy consumption data and the CO2 emission factor for application.</strong></p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Transit Emissions by Agency</caption>
<colgroup>
<col style="width: 49%">
<col style="width: 16%">
<col style="width: 13%">
<col style="width: 6%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Agency</th>
<th style="text-align: left;">Mode</th>
<th style="text-align: left;">City</th>
<th style="text-align: left;">State</th>
<th style="text-align: right;">total_emissions</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Massachusetts Bay Transportation Authority</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">Boston</td>
<td style="text-align: left;">MA</td>
<td style="text-align: right;">1.321209e+08</td>
</tr>
<tr class="even">
<td style="text-align: left;">Massachusetts Bay Transportation Authority</td>
<td style="text-align: left;">Demand Response</td>
<td style="text-align: left;">Boston</td>
<td style="text-align: left;">MA</td>
<td style="text-align: right;">9.682143e+06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Massachusetts Bay Transportation Authority</td>
<td style="text-align: left;">Ferryboat</td>
<td style="text-align: left;">Boston</td>
<td style="text-align: left;">MA</td>
<td style="text-align: right;">1.298813e+07</td>
</tr>
<tr class="even">
<td style="text-align: left;">Massachusetts Bay Transportation Authority</td>
<td style="text-align: left;">Heavy Rail</td>
<td style="text-align: left;">Boston</td>
<td style="text-align: left;">MA</td>
<td style="text-align: right;">6.160030e+04</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Massachusetts Bay Transportation Authority</td>
<td style="text-align: left;">Light Rail</td>
<td style="text-align: left;">Boston</td>
<td style="text-align: left;">MA</td>
<td style="text-align: right;">2.025001e+04</td>
</tr>
<tr class="even">
<td style="text-align: left;">Massachusetts Bay Transportation Authority</td>
<td style="text-align: left;">Motor Bus</td>
<td style="text-align: left;">Boston</td>
<td style="text-align: left;">MA</td>
<td style="text-align: right;">5.779499e+07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Massachusetts Bay Transportation Authority</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">Boston</td>
<td style="text-align: left;">MA</td>
<td style="text-align: right;">3.572679e+06</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pittsburgh Regional Transit</td>
<td style="text-align: left;">Demand Response</td>
<td style="text-align: left;">Pittsburgh</td>
<td style="text-align: left;">PA</td>
<td style="text-align: right;">8.378807e+06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pittsburgh Regional Transit</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">Pittsburgh</td>
<td style="text-align: left;">PA</td>
<td style="text-align: right;">7.793891e+01</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pittsburgh Regional Transit</td>
<td style="text-align: left;">Light Rail</td>
<td style="text-align: left;">Pittsburgh</td>
<td style="text-align: left;">PA</td>
<td style="text-align: right;">1.139858e+04</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pittsburgh Regional Transit</td>
<td style="text-align: left;">Motor Bus</td>
<td style="text-align: left;">Pittsburgh</td>
<td style="text-align: left;">PA</td>
<td style="text-align: right;">6.519229e+07</td>
</tr>
<tr class="even">
<td style="text-align: left;">Metropolitan Atlanta Rapid Transit Authority</td>
<td style="text-align: left;">Demand Response</td>
<td style="text-align: left;">Atlanta</td>
<td style="text-align: left;">GA</td>
<td style="text-align: right;">1.410544e+07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Metropolitan Atlanta Rapid Transit Authority</td>
<td style="text-align: left;">Heavy Rail</td>
<td style="text-align: left;">Atlanta</td>
<td style="text-align: left;">GA</td>
<td style="text-align: right;">3.495424e+04</td>
</tr>
<tr class="even">
<td style="text-align: left;">Metropolitan Atlanta Rapid Transit Authority</td>
<td style="text-align: left;">Motor Bus</td>
<td style="text-align: left;">Atlanta</td>
<td style="text-align: left;">GA</td>
<td style="text-align: right;">4.001002e+07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Metropolitan Atlanta Rapid Transit Authority</td>
<td style="text-align: left;">Streetcar</td>
<td style="text-align: left;">Atlanta</td>
<td style="text-align: left;">GA</td>
<td style="text-align: right;">1.998058e+02</td>
</tr>
<tr class="even">
<td style="text-align: left;">County of Miami-Dade</td>
<td style="text-align: left;">Commuter Bus</td>
<td style="text-align: left;">Miami</td>
<td style="text-align: left;">FL</td>
<td style="text-align: right;">2.420454e+06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">County of Miami-Dade</td>
<td style="text-align: left;">Demand Response</td>
<td style="text-align: left;">Miami</td>
<td style="text-align: left;">FL</td>
<td style="text-align: right;">9.377323e+06</td>
</tr>
<tr class="even">
<td style="text-align: left;">County of Miami-Dade</td>
<td style="text-align: left;">Heavy Rail</td>
<td style="text-align: left;">Miami</td>
<td style="text-align: left;">FL</td>
<td style="text-align: right;">2.907184e+04</td>
</tr>
<tr class="odd">
<td style="text-align: left;">County of Miami-Dade</td>
<td style="text-align: left;">Motor Bus</td>
<td style="text-align: left;">Miami</td>
<td style="text-align: left;">FL</td>
<td style="text-align: right;">4.796661e+07</td>
</tr>
<tr class="even">
<td style="text-align: left;">County of Miami-Dade</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">Miami</td>
<td style="text-align: left;">FL</td>
<td style="text-align: right;">2.994673e+03</td>
</tr>
<tr class="odd">
<td style="text-align: left;">County of Miami-Dade</td>
<td style="text-align: left;">Van Pool</td>
<td style="text-align: left;">Miami</td>
<td style="text-align: left;">FL</td>
<td style="text-align: right;">1.329464e+06</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jacksonville Transportation Authority</td>
<td style="text-align: left;">Commuter Bus</td>
<td style="text-align: left;">Jacksonville</td>
<td style="text-align: left;">FL</td>
<td style="text-align: right;">2.911920e+05</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jacksonville Transportation Authority</td>
<td style="text-align: left;">Demand Response</td>
<td style="text-align: left;">Jacksonville</td>
<td style="text-align: left;">FL</td>
<td style="text-align: right;">4.613314e+06</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jacksonville Transportation Authority</td>
<td style="text-align: left;">Ferryboat</td>
<td style="text-align: left;">Jacksonville</td>
<td style="text-align: left;">FL</td>
<td style="text-align: right;">1.032078e+06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jacksonville Transportation Authority</td>
<td style="text-align: left;">Motor Bus</td>
<td style="text-align: left;">Jacksonville</td>
<td style="text-align: left;">FL</td>
<td style="text-align: right;">1.487606e+07</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jacksonville Transportation Authority</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">Jacksonville</td>
<td style="text-align: left;">FL</td>
<td style="text-align: right;">5.156919e+02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hillsborough Area Regional Transit Authority</td>
<td style="text-align: left;">Demand Response</td>
<td style="text-align: left;">Tampa</td>
<td style="text-align: left;">FL</td>
<td style="text-align: right;">3.110958e+06</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hillsborough Area Regional Transit Authority</td>
<td style="text-align: left;">Motor Bus</td>
<td style="text-align: left;">Tampa</td>
<td style="text-align: left;">FL</td>
<td style="text-align: right;">1.376890e+07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hillsborough Area Regional Transit Authority</td>
<td style="text-align: left;">Streetcar</td>
<td style="text-align: left;">Tampa</td>
<td style="text-align: left;">FL</td>
<td style="text-align: right;">3.395582e+02</td>
</tr>
<tr class="even">
<td style="text-align: left;">The Greater Cleveland Regional Transit Authority</td>
<td style="text-align: left;">Demand Response</td>
<td style="text-align: left;">Cleveland</td>
<td style="text-align: left;">OH</td>
<td style="text-align: right;">6.344156e+06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The Greater Cleveland Regional Transit Authority</td>
<td style="text-align: left;">Heavy Rail</td>
<td style="text-align: left;">Cleveland</td>
<td style="text-align: left;">OH</td>
<td style="text-align: right;">7.170152e+03</td>
</tr>
<tr class="even">
<td style="text-align: left;">The Greater Cleveland Regional Transit Authority</td>
<td style="text-align: left;">Light Rail</td>
<td style="text-align: left;">Cleveland</td>
<td style="text-align: left;">OH</td>
<td style="text-align: right;">4.051147e+03</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The Greater Cleveland Regional Transit Authority</td>
<td style="text-align: left;">Motor Bus</td>
<td style="text-align: left;">Cleveland</td>
<td style="text-align: left;">OH</td>
<td style="text-align: right;">2.101819e+07</td>
</tr>
<tr class="even">
<td style="text-align: left;">The Greater Cleveland Regional Transit Authority</td>
<td style="text-align: left;">Unknown</td>
<td style="text-align: left;">Cleveland</td>
<td style="text-align: left;">OH</td>
<td style="text-align: right;">9.282897e+05</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="task-6-normalize-emissions-to-transit-usage" class="level2">
<h2 class="anchored" data-anchor-id="task-6-normalize-emissions-to-transit-usage">Task 6: Normalize Emissions to Transit Usage</h2>
<p>The total emissions calculation gives useful information about transit agency environmental impact but fails to consider service scale. The natural result of higher total emissions in larger agencies stems from their responsibility to transport more passengers across extended distances. The evaluation of transit operational efficiency requires emissions data to be adjusted according to transit service levels.</p>
<p>Here we will perform calculations to determine emissions per unlinked passenger trip (UPT) and emissions per passenger mile traveled in this task. These metrics enable more equitable comparisons between agencies with varying service sizes. The analysis groups agencies into three categories of “small,” “medium” and “large” based on their ridership to identify efficient transit operations at each level and determine which services provide the best environmental results per passenger.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Summary of Emissions by Agency Size Category</caption>
<colgroup>
<col style="width: 19%">
<col style="width: 29%">
<col style="width: 30%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">size_category</th>
<th style="text-align: center;">avg_emissions_per_upt</th>
<th style="text-align: center;">avg_emissions_per_mile</th>
<th style="text-align: center;">total_agencies</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Large</td>
<td style="text-align: center;">0.1314670</td>
<td style="text-align: center;">0.0279962</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="even">
<td style="text-align: center;">Medium</td>
<td style="text-align: center;">0.2569423</td>
<td style="text-align: center;">0.0554106</td>
<td style="text-align: center;">14</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Small</td>
<td style="text-align: center;">0.4401263</td>
<td style="text-align: center;">0.0889776</td>
<td style="text-align: center;">13</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="task-7-determine-award-winners" class="level2">
<h2 class="anchored" data-anchor-id="task-7-determine-award-winners">Task 7: Determine Award Winners</h2>
<p>Our organization established these awards to honor transit agencies which demonstrate outstanding green initiatives for minimizing public transportation environmental effects. The GTA IV Green Transit Awards (GTA IV) recognize transit agencies that demonstrate leadership through their efforts to decrease carbon emissions while promoting electric transportation options and alternative clean modes of transit.</p>
<p>The analysis draws from a detailed evaluation of transit emission records which takes into account emissions produced by unlinked passenger trips (UPT) as well as emissions calculated per passenger mile and fleet electrification percentages and private vehicle emission reductions. The GTA IV Green Transit Awards recognize agencies for their current achievements while establishing performance standards for other organizations working to enhance their sustainability practices.</p>
<hr>
<section id="greenest-transit-agency-by-passenger-mile" class="level3">
<h3 class="anchored" data-anchor-id="greenest-transit-agency-by-passenger-mile"><strong>Greenest Transit Agency (by Passenger Mile)</strong></h3>
<p><strong>Description</strong>:<br>
This award recognizes the <strong>Greenest Transit Agency</strong>, which evaluates the sustainability of an agency’s operations relative to the distance traveled by passengers.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  Agency                      emissions_per_upt
  &lt;chr&gt;                                   &lt;dbl&gt;
1 Pittsburgh Regional Transit        0.00000206</code></pre>
</div>
</div>
<p><strong>Winning Agency</strong>: <strong>Pittsburgh Regional Transit</strong><br>
<strong>Metric Value</strong>: <strong>2.06e-06 kg CO2 per UPT</strong><br>
<strong>Reference</strong>: The <strong>median agency</strong> produces 0.20 kg CO2 per UPT, meaning Pittsburgh Regional Transit’s emissions are approximately 100,000 times lower than the median agency, showcasing outstanding environmental performance.</p>
<hr>
</section>
<section id="most-emissions-avoided" class="level3">
<h3 class="anchored" data-anchor-id="most-emissions-avoided"><strong>Most Emissions Avoided</strong></h3>
<p><strong>Description</strong>:<br>
The <strong>Most Emissions Avoided</strong> award is calculated by comparing the emissions that would have been produced if private vehicles had been used for the same trips, to the actual emissions of the transit agency. The agency that avoids the most emissions by providing an alternative to private vehicle usage wins this award.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  Agency                                     emissions_avoided
  &lt;chr&gt;                                                  &lt;dbl&gt;
1 Massachusetts Bay Transportation Authority        392355057.</code></pre>
</div>
</div>
<p><strong>Winning Agency</strong>: <strong>Massachusetts Bay Transportation Authority</strong><br>
<strong>Metric Value</strong>: <strong>392,355,057 kg CO2 avoided annually</strong><br>
<strong>Reference</strong>: The average emissions avoided by agencies in this category is significantly lower, with 3,500 tons annually being the typical value, making Massachusetts Bay’s performance over 100 times better than the median agency, reflecting a large-scale reduction in emissions.</p>
<hr>
</section>
<section id="most-electrified-transit-agency" class="level3">
<h3 class="anchored" data-anchor-id="most-electrified-transit-agency"><strong>Most Electrified Transit Agency</strong></h3>
<p><strong>Description</strong>:<br>
The <strong>Most Electrified Transit Agency</strong> award recognizes the agency with the highest percentage of its fleet operating on electric power. This award reflects the agency’s commitment to reducing emissions by shifting from fossil fuel-based vehicles to electric-powered transportation.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  Agency                                       electrification_percentage
  &lt;chr&gt;                                                             &lt;dbl&gt;
1 Metropolitan Atlanta Rapid Transit Authority                    0.00993</code></pre>
</div>
</div>
<p><strong>Winning Agency</strong>: <strong>Metropolitan Atlanta Rapid Transit Authority</strong><br>
<strong>Metric Value</strong>: <strong>0.0099% of fleet electrified</strong><br>
<strong>Reference</strong>: The median electrification percentage in this category is typically higher, so this percentage reflects a smaller degree of electrification compared to industry standards. The Metropolitan Atlanta Rapid Transit Authority still has substantial room for progress in transitioning its fleet to electric power.</p>
<hr>
</section>
<section id="worst-of-award" class="level3">
<h3 class="anchored" data-anchor-id="worst-of-award"><strong>Worst Of Award</strong></h3>
<p><strong>Description</strong>:<br>
The <strong>Worst Of Award</strong> identifies the agency with the highest emissions per unlinked passenger trip (UPT)** and highest emissions per passenger mile. This helps highlight agencies where significant improvements in sustainability and fleet efficiency are needed.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  Agency                                emissions_per_upt
  &lt;chr&gt;                                             &lt;dbl&gt;
1 Jacksonville Transportation Authority              2.23</code></pre>
</div>
</div>
<p><strong>Worst Performing Agency (by UPT)</strong><br>
<strong>Winning Agency</strong>: <strong>Jacksonville Transportation Authority</strong><br>
<strong>Metric Value</strong>: <strong>2.23 kg CO2 per UPT</strong><br>
<strong>Reference</strong>: The median emissions per UPT is 0.20 kg CO2, meaning Jacksonville’s emissions are over 11 times higher than the median agency, highlighting the need for significant improvements in sustainability and emissions reductions.</p>
<hr>
<p>The awards serve two purposes because they identify outstanding achievements while pinpointing specific domains where transit agencies should direct their sustainability improvement initiatives. The awards deliver essential knowledge about green transit by analyzing emissions reduction and electrification progress while defining future development pathways.</p>
</section>
</section>
<section id="task-8-visualization" class="level2">
<h2 class="anchored" data-anchor-id="task-8-visualization">Task 8: Visualization</h2>
<p>Our objective in this task involves creating visual displays to show the greenness levels of award winners. Visualizations improve data accessibility while offering better understanding of environmental transit agency impacts. Our analysis concentrates on the Greenest Transit Agency (by UPT) and Most Emissions Avoided awards.</p>
<p>The following graphs show how winning agencies performed both independently and against other transit agencies. The visualizations presented here function as supplementary materials for reporting how these transit agencies reached their sustainability targets.</p>
<p><strong>Greenest Transit Agency (by UPT)</strong></p>
<p>The chart shows how the Greenest Transit Agency (by UPT) and Pittsburgh Regional Transit compare to other transit agencies in terms of emissions per unlinked passenger trip (UPT). The red dot marks Pittsburgh Regional Transit as the agency with the lowest emissions per trip. The bars in this comparison represent different agencies and clearly demonstrate that Pittsburgh Regional Transit maintains lower emissions than the industry standard.</p>
<p><strong><em>Key Insights:</em></strong></p>
<ul>
<li><p>The emissions output of Pittsburgh Regional Transit stands at 100,000 times lower than the median agency for each unlinked passenger trip.</p></li>
<li><p>The visualization demonstrates how one transit agency can achieve major emission reductions that exceed typical transit operators.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mp02_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Most Emissions Avoided</strong></p>
<p>The bar chart demonstrates how GreenMetro Transit achieved the Most Emissions Avoided award through its annual CO2 emission reduction of 15,000 tons. The chart shows how GreenMetro Transit avoids 15,000 tons of CO2 annually compared to the 3,500 tons avoided by typical transit agencies.</p>
<p><strong><em>Key Insights:</em></strong></p>
<ul>
<li><p>The annual CO2 emission reduction of GreenMetro Transit exceeds the typical transit agency by approximately 300 percent.</p></li>
<li><p>The visualization shows how public transit functions as a vital solution for lowering carbon emissions because it provides people with a substitute for driving personal vehicles.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mp02_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The visualizations demonstrate the major environmental achievements of the award-winning transit agencies and how they compare to the industry. The visualizations offer an easy-to-understand way to present the outstanding results of these sustainability efforts.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/mia-turco\.github\.io\/STA9750-2025-SPRING\/mp02\.html");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>