<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>MP03: Spotify Song Analytics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="mp03_files/libs/clipboard/clipboard.min.js"></script>
<script src="mp03_files/libs/quarto-html/quarto.js"></script>
<script src="mp03_files/libs/quarto-html/popper.min.js"></script>
<script src="mp03_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="mp03_files/libs/quarto-html/anchor.min.js"></script>
<link href="mp03_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="mp03_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="mp03_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="mp03_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="mp03_files/libs/bootstrap/bootstrap-49b8e94740e001a83ae21307f502e232.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


<link rel="stylesheet" href="styles.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#initial-exploration" id="toc-initial-exploration" class="nav-link" data-scroll-target="#initial-exploration">Initial Exploration</a>
  <ul class="collapse">
  <li><a href="#how-many-distinct-tracks-and-artists-are-represented-in-the-playlist-data" id="toc-how-many-distinct-tracks-and-artists-are-represented-in-the-playlist-data" class="nav-link" data-scroll-target="#how-many-distinct-tracks-and-artists-are-represented-in-the-playlist-data">1. How many distinct tracks and artists are represented in the playlist data?</a></li>
  <li><a href="#what-are-the-5-most-popular-tracks-in-the-playlist-data" id="toc-what-are-the-5-most-popular-tracks-in-the-playlist-data" class="nav-link" data-scroll-target="#what-are-the-5-most-popular-tracks-in-the-playlist-data">2. What are the 5 most popular tracks in the playlist data?</a></li>
  <li><a href="#what-is-the-most-popular-track-in-the-playlist-data-that-does-not-have-a-corresponding-entry-in-the-song-characteristics-data" id="toc-what-is-the-most-popular-track-in-the-playlist-data-that-does-not-have-a-corresponding-entry-in-the-song-characteristics-data" class="nav-link" data-scroll-target="#what-is-the-most-popular-track-in-the-playlist-data-that-does-not-have-a-corresponding-entry-in-the-song-characteristics-data">3. What is the most popular track in the playlist data that does <em>not</em> have a corresponding entry in the song characteristics data?</a></li>
  <li><a href="#according-to-the-song-characteristics-data-what-is-the-most-danceable-track-how-often-does-it-appear-in-a-playlist" id="toc-according-to-the-song-characteristics-data-what-is-the-most-danceable-track-how-often-does-it-appear-in-a-playlist" class="nav-link" data-scroll-target="#according-to-the-song-characteristics-data-what-is-the-most-danceable-track-how-often-does-it-appear-in-a-playlist">4. According to the song characteristics data, what is the most “danceable” track? How often does it appear in a playlist?</a></li>
  <li><a href="#which-playlist-has-the-longest-average-track-length" id="toc-which-playlist-has-the-longest-average-track-length" class="nav-link" data-scroll-target="#which-playlist-has-the-longest-average-track-length">5. Which playlist has the longest average track length?</a></li>
  <li><a href="#what-is-the-most-popular-playlist-on-spotify" id="toc-what-is-the-most-popular-playlist-on-spotify" class="nav-link" data-scroll-target="#what-is-the-most-popular-playlist-on-spotify">6. What is the most popular playlist on Spotify?</a></li>
  </ul></li>
  <li><a href="#identifying-characteristics-of-popular-songs" id="toc-identifying-characteristics-of-popular-songs" class="nav-link" data-scroll-target="#identifying-characteristics-of-popular-songs">Identifying Characteristics of Popular Songs</a>
  <ul class="collapse">
  <li><a href="#is-the-popularity-column-correlated-with-the-number-of-playlist-appearances" id="toc-is-the-popularity-column-correlated-with-the-number-of-playlist-appearances" class="nav-link" data-scroll-target="#is-the-popularity-column-correlated-with-the-number-of-playlist-appearances">1. Is the popularity column correlated with the number of playlist appearances?</a></li>
  <li><a href="#in-what-year-were-the-most-popular-songs-released" id="toc-in-what-year-were-the-most-popular-songs-released" class="nav-link" data-scroll-target="#in-what-year-were-the-most-popular-songs-released">2. In what year were the most popular songs released?</a></li>
  <li><a href="#in-what-year-did-danceability-peak" id="toc-in-what-year-did-danceability-peak" class="nav-link" data-scroll-target="#in-what-year-did-danceability-peak">3. In what year did danceability peak?</a></li>
  <li><a href="#which-decade-is-most-represented-on-user-playlists" id="toc-which-decade-is-most-represented-on-user-playlists" class="nav-link" data-scroll-target="#which-decade-is-most-represented-on-user-playlists">4. Which decade is most represented on user playlists?</a></li>
  <li><a href="#musical-key-distribution-polar-plot" id="toc-musical-key-distribution-polar-plot" class="nav-link" data-scroll-target="#musical-key-distribution-polar-plot">5. Musical Key Distribution (Polar Plot)</a></li>
  <li><a href="#what-are-the-most-popular-track-lengths" id="toc-what-are-the-most-popular-track-lengths" class="nav-link" data-scroll-target="#what-are-the-most-popular-track-lengths">6. What Are the Most Popular Track Lengths?</a></li>
  <li><a href="#are-popular-songs-more-danceable" id="toc-are-popular-songs-more-danceable" class="nav-link" data-scroll-target="#are-popular-songs-more-danceable">7. Are Popular Songs More Danceable?</a></li>
  <li><a href="#are-explicit-songs-more-popular" id="toc-are-explicit-songs-more-popular" class="nav-link" data-scroll-target="#are-explicit-songs-more-popular">8. Are Explicit Songs More Popular?</a></li>
  </ul></li>
  <li><a href="#task-6-building-a-playlist-from-anchor-songs" id="toc-task-6-building-a-playlist-from-anchor-songs" class="nav-link" data-scroll-target="#task-6-building-a-playlist-from-anchor-songs">Task 6: Building a Playlist from Anchor Songs</a>
  <ul class="collapse">
  <li><a href="#songs-commonly-found-on-the-same-playlists" id="toc-songs-commonly-found-on-the-same-playlists" class="nav-link" data-scroll-target="#songs-commonly-found-on-the-same-playlists">1. Songs Commonly Found on the Same Playlists</a></li>
  <li><a href="#songs-in-the-same-key-and-tempo-range" id="toc-songs-in-the-same-key-and-tempo-range" class="nav-link" data-scroll-target="#songs-in-the-same-key-and-tempo-range">2. Songs in the Same Key and Tempo Range</a></li>
  <li><a href="#songs-by-the-same-artist" id="toc-songs-by-the-same-artist" class="nav-link" data-scroll-target="#songs-by-the-same-artist">3. Songs by the Same Artist</a></li>
  <li><a href="#songs-from-the-same-era-with-similar-sound" id="toc-songs-from-the-same-era-with-similar-sound" class="nav-link" data-scroll-target="#songs-from-the-same-era-with-similar-sound">4. Songs from the Same Era with Similar Sound</a></li>
  <li><a href="#hidden-gems" id="toc-hidden-gems" class="nav-link" data-scroll-target="#hidden-gems">5. Hidden Gems</a></li>
  </ul></li>
  <li><a href="#task-7-creating-the-ultimate-playlist" id="toc-task-7-creating-the-ultimate-playlist" class="nav-link" data-scroll-target="#task-7-creating-the-ultimate-playlist">Task 7: Creating The Ultimate Playlist</a></li>
  <li><a href="#the-ultimate-playlist-rock-vinyl-classics" id="toc-the-ultimate-playlist-rock-vinyl-classics" class="nav-link" data-scroll-target="#the-ultimate-playlist-rock-vinyl-classics">The Ultimate Playlist: <em>Rock Vinyl Classics</em></a>
  <ul class="collapse">
  <li><a href="#description" id="toc-description" class="nav-link" data-scroll-target="#description">📝 Description</a></li>
  <li><a href="#design-principles" id="toc-design-principles" class="nav-link" data-scroll-target="#design-principles">🎧 Design Principles</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">MP03: Spotify Song Analytics</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>This mini-project investigates Spotify song characteristics to discover which elements make tracks popular. We start by analyzing both the structure and variables within the dataset. In this mini-project, we’ll explore Spotify song characteristics and playlists using two external datasets mirrored from GitHub. We’ll begin by downloading and preparing the song data, followed by extracting and cleaning playlist-level information.</p>
<hr>
</section>
<section id="initial-exploration" class="level2">
<h2 class="anchored" data-anchor-id="initial-exploration">Initial Exploration</h2>
<p>Let’s examine the data scope before moving forward with detailed analysis. The dataset contains what total number of distinct songs and artists? Which specific tracks appear most frequently across playlists? Do any playlists or songs stand out from the rest as unexpected discoveries?</p>
<p>The questions guide us to understand our data as both numerical information and as evidence of how listeners behave and cultural patterns evolve.</p>
<hr>
<section id="how-many-distinct-tracks-and-artists-are-represented-in-the-playlist-data" class="level3">
<h3 class="anchored" data-anchor-id="how-many-distinct-tracks-and-artists-are-represented-in-the-playlist-data">1. How many distinct tracks and artists are represented in the playlist data?</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  `Distinct Tracks` `Distinct Artist`
              &lt;int&gt;             &lt;int&gt;
1             34443              9754</code></pre>
</div>
</div>
<p>The number of unique tracks is 34443 and the number of unique artists is 9754. This gives us an idea of how diverse the content is.</p>
<hr>
</section>
<section id="what-are-the-5-most-popular-tracks-in-the-playlist-data" class="level3">
<h3 class="anchored" data-anchor-id="what-are-the-5-most-popular-tracks-in-the-playlist-data">2. What are the 5 most popular tracks in the playlist data?</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  track_name                      n
  &lt;chr&gt;                       &lt;int&gt;
1 Closer                         75
2 One Dance                      55
3 HUMBLE.                        52
4 Ride                           52
5 Broccoli (feat. Lil Yachty)    50</code></pre>
</div>
</div>
<p>The five most frequently appearing tracks in playlists are shown above. They may not be current hits, but they represent what was most frequently added at the time the data was collected.</p>
<hr>
</section>
<section id="what-is-the-most-popular-track-in-the-playlist-data-that-does-not-have-a-corresponding-entry-in-the-song-characteristics-data" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-most-popular-track-in-the-playlist-data-that-does-not-have-a-corresponding-entry-in-the-song-characteristics-data">3. What is the most popular track in the playlist data that does <em>not</em> have a corresponding entry in the song characteristics data?</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  track_name     n
  &lt;chr&gt;      &lt;int&gt;
1 One Dance     55</code></pre>
</div>
</div>
<p>The track “One Dance” appears frequently in playlists yet fails to appear in the song analytics dataset which suggests a possible time difference between dataset exports.</p>
<hr>
</section>
<section id="according-to-the-song-characteristics-data-what-is-the-most-danceable-track-how-often-does-it-appear-in-a-playlist" class="level3">
<h3 class="anchored" data-anchor-id="according-to-the-song-characteristics-data-what-is-the-most-danceable-track-how-often-does-it-appear-in-a-playlist">4. According to the song characteristics data, what is the most “danceable” track? How often does it appear in a playlist?</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  name              artists      danceability playlist_appearances
  &lt;chr&gt;             &lt;chr&gt;               &lt;dbl&gt;                &lt;int&gt;
1 Funky Cold Medina ['Tone-Loc']        0.988                    1</code></pre>
</div>
</div>
<p>The tool reveals the most popular danceable track to be “Funky Cold Medina” along with its playlist frequency which links track-level analytics to actual playlist behavior.</p>
<hr>
</section>
<section id="which-playlist-has-the-longest-average-track-length" class="level3">
<h3 class="anchored" data-anchor-id="which-playlist-has-the-longest-average-track-length">5. Which playlist has the longest average track length?</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  playlist_id playlist_name avg_duration
        &lt;int&gt; &lt;chr&gt;                &lt;dbl&gt;
1         667 classical          411149.</code></pre>
</div>
</div>
<p>The classical playlist seems to prefer longer songs, which is typical of the genre.</p>
<hr>
</section>
<section id="what-is-the-most-popular-playlist-on-spotify" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-most-popular-playlist-on-spotify">6. What is the most popular playlist on Spotify?</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  playlist_id playlist_name playlist_followers
        &lt;int&gt; &lt;chr&gt;                      &lt;int&gt;
1         765 Tangled                     1038</code></pre>
</div>
</div>
<p>The playlist with the highest follower count in the dataset is “Tangled”.</p>
</section>
</section>
<section id="identifying-characteristics-of-popular-songs" class="level2">
<h2 class="anchored" data-anchor-id="identifying-characteristics-of-popular-songs">Identifying Characteristics of Popular Songs</h2>
<p>We have examined which songs and artists appear in the data so we will now examine the features that determine popularity. What characteristics make a song more likely to be included in playlists? Do popular tracks tend to have specific features such as danceability, key or track length?</p>
<p>These questions will be answered by a set of visualizations that show patterns in tracks, release years and musical traits.</p>
<hr>
<section id="is-the-popularity-column-correlated-with-the-number-of-playlist-appearances" class="level3">
<h3 class="anchored" data-anchor-id="is-the-popularity-column-correlated-with-the-number-of-playlist-appearances">1. Is the popularity column correlated with the number of playlist appearances?</h3>
<p>The popularity score of each track on Spotify ranges from 0 to 100 and depends on streaming numbers and recent activity along with other engagement metrics. The graph shows popularity ratings against playlist occurrence frequency for each song.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mp03_files/figure-html/popularity-vs-appearances-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The analysis reveals a weak positive pattern between playlist inclusion frequency and popularity scores yet numerous popular songs fail to appear in playlists.</p>
<hr>
</section>
<section id="in-what-year-were-the-most-popular-songs-released" class="level3">
<h3 class="anchored" data-anchor-id="in-what-year-were-the-most-popular-songs-released">2. In what year were the most popular songs released?</h3>
<p>Do listeners mostly listen to new songs or do they stick to older hits?</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mp03_files/figure-html/most-popular-years-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Our results imply that the most popular songs were released in the 20th century.</p>
<hr>
</section>
<section id="in-what-year-did-danceability-peak" class="level3">
<h3 class="anchored" data-anchor-id="in-what-year-did-danceability-peak">3. In what year did danceability peak?</h3>
<p>We will calculate the average danceability score by release year to see when “dancability” peaked.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mp03_files/figure-html/danceability-by-year-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Our graph shows that dancability had a steep rise in popularity in the late 40’s and had similar peaks in the 1980’s and 2000’s.</p>
<hr>
</section>
<section id="which-decade-is-most-represented-on-user-playlists" class="level3">
<h3 class="anchored" data-anchor-id="which-decade-is-most-represented-on-user-playlists">4. Which decade is most represented on user playlists?</h3>
<p>The following analysis groups songs by decade to reveal which musical eras appear most frequently in user-created playlists.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mp03_files/figure-html/top-decades-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It appears as though the 2010’s are the most popular decade in user-created playlists.</p>
<hr>
</section>
<section id="musical-key-distribution-polar-plot" class="level3">
<h3 class="anchored" data-anchor-id="musical-key-distribution-polar-plot">5. Musical Key Distribution (Polar Plot)</h3>
<p>The musical keys exist in a natural cycle which we call the circle of fifths. The frequency of key usage will be represented through polar coordinates in a circular plot.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mp03_files/figure-html/key-polar-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Keys such as C, C#/D♭ and G appear to be used more frequently than keys suchs as D#/E and A#/B♭.</p>
<hr>
</section>
<section id="what-are-the-most-popular-track-lengths" class="level3">
<h3 class="anchored" data-anchor-id="what-are-the-most-popular-track-lengths">6. What Are the Most Popular Track Lengths?</h3>
<p>Do users prefer shorter songs, longer ballads, or something in between? Let’s find out by plotting track durations.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mp03_files/figure-html/track-length-distribution-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The typical track length appears to be around 3-4 minutes long.</p>
<hr>
</section>
<section id="are-popular-songs-more-danceable" class="level3">
<h3 class="anchored" data-anchor-id="are-popular-songs-more-danceable">7. Are Popular Songs More Danceable?</h3>
<p>Let’s compare average danceability across different popularity levels.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mp03_files/figure-html/danceability-vs-popularity-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The correlation between Dancability and Popularity seems to be weak and scattered.</p>
<hr>
</section>
<section id="are-explicit-songs-more-popular" class="level3">
<h3 class="anchored" data-anchor-id="are-explicit-songs-more-popular">8. Are Explicit Songs More Popular?</h3>
<p>Let’s compare the correlation betweenpopularity and explicitly.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mp03_files/figure-html/explicit-vs-popularity-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The popularity scores of explicit songs are slightly higher than those of non-explicit songs which indicates a weak relationship between explicit content and mainstream appeal.</p>
<hr>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 3
   name                                               artists                  n
   &lt;chr&gt;                                              &lt;chr&gt;                &lt;int&gt;
 1 "Stairway to Heaven - 2012 Remaster"               ['Led Zeppelin']        17
 2 "Fortunate Son"                                    ['Creedence Clearwa…    16
 3 "Landslide"                                        ['Fleetwood Mac']       12
 4 "Dreams - 2004 Remaster"                           ['Fleetwood Mac']        9
 5 "The Sound of Silence - Acoustic Version"          ['Simon &amp; Garfunkel…     9
 6 "Beast Of Burden - Remastered"                     ['The Rolling Stone…     8
 7 "Whole Lotta Love - 1990 Remaster"                 ['Led Zeppelin']         8
 8 "Another Brick in the Wall, Pt. 2"                 ['Pink Floyd']           7
 9 "Down On The Corner"                               ['Creedence Clearwa…     7
10 "Mrs. Robinson - From \"The Graduate\" Soundtrack" ['Simon &amp; Garfunkel…     7
11 "Purple Haze"                                      ['Jimi Hendrix']         7
12 "Good Times Bad Times - 1993 Remaster"             ['Led Zeppelin']         6
13 "Rock and Roll - 2012 Remaster"                    ['Led Zeppelin']         6
14 "Up Around The Bend"                               ['Creedence Clearwa…     6
15 "Wouldn't It Be Nice - Stereo Mix"                 ['The Beach Boys']       6</code></pre>
</div>
</div>
</section>
</section>
<section id="task-6-building-a-playlist-from-anchor-songs" class="level2">
<h2 class="anchored" data-anchor-id="task-6-building-a-playlist-from-anchor-songs">Task 6: Building a Playlist from Anchor Songs</h2>
<p>What makes a great playlist? It’s not just about individual songs, but rather it’s about flow, cohesion, and musical compatibility. To explore this, we’ll start with two anchor songs and use a mix of musical and behavioral heuristics to find tracks that complement them.</p>
<p>For this task, we’ve chosen:</p>
<ul>
<li>🎸 <strong>“Stairway to Heaven – 2012 Remaster”</strong> by <em>Led Zeppelin</em><br>
</li>
<li>🇺🇸 <strong>“Fortunate Son”</strong> by <em>Creedence Clearwater Revival</em></li>
</ul>
<p>These two songs are rock classics that define a popular music sound for many people.</p>
<p>We’ll now explore five strategies to find songs that belong alongside them.</p>
<hr>
<section id="songs-commonly-found-on-the-same-playlists" class="level3">
<h3 class="anchored" data-anchor-id="songs-commonly-found-on-the-same-playlists">1. Songs Commonly Found on the Same Playlists</h3>
<p>The following list shows the most frequently appearing songs on playlists that include either <em>Stairway to Heaven</em> or <em>Fortunate Son</em>. These tracks may not be musically identical, but they reflect the tastes of users who grouped them with our anchors — a strong signal of perceived compatibility.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 3
   name                             artists                     n
   &lt;chr&gt;                            &lt;chr&gt;                   &lt;int&gt;
 1 Carry on Wayward Son             ['Kansas']                 13
 2 Brown Eyed Girl                  ['Van Morrison']           12
 3 Hotel California - 2013 Remaster ['Eagles']                 12
 4 More Than a Feeling              ['Boston']                 12
 5 Sweet Emotion                    ['Aerosmith']              10
 6 Dream On                         ['Aerosmith']               9
 7 House Of The Rising Sun          ['The Animals']             9
 8 Piano Man                        ['Billy Joel']              9
 9 Thunderstruck                    ['AC/DC']                   9
10 American Pie                     ['Don McLean']              8
11 For What It's Worth              ['Buffalo Springfield']     8
12 Free Bird                        ['Lynyrd Skynyrd']          8
13 Highway to Hell                  ['AC/DC']                   8</code></pre>
</div>
</div>
<hr>
</section>
<section id="songs-in-the-same-key-and-tempo-range" class="level3">
<h3 class="anchored" data-anchor-id="songs-in-the-same-key-and-tempo-range">2. Songs in the Same Key and Tempo Range</h3>
<p>These tracks share the same musical key and tempo range as the anchor songs to create a continuous listening flow.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 4
   name                                               artists          key tempo
   &lt;chr&gt;                                              &lt;chr&gt;          &lt;dbl&gt; &lt;dbl&gt;
 1 "Twenty Miles"                                     ['Deer Tick']      0 114. 
 2 "Maybe IDK"                                        ['Jon Bellion…     9 120. 
 3 "Fixer Upper - From \"Frozen\"/Soundtrack Version" ['Maia Wilson…     9 103. 
 4 "Check"                                            ['Young Thug']     0 111. 
 5 "Suffocate - Superclean"                           ['J. Holiday']     9  82.8
 6 "Double Vision"                                    ['Foreigner']      9 130. 
 7 "When I'm Gone"                                    ['Wiz Khalifa…     9  92.0
 8 "The Lemon Song - 1993 Remaster"                   ['Led Zeppeli…     9  90.5
 9 "The Big Rock Candy Mountain"                      ['Harry McCli…     0  94.5
10 "Cell Therapy"                                     ['Goodie Mob']     0  83.1</code></pre>
</div>
</div>
<hr>
</section>
<section id="songs-by-the-same-artist" class="level3">
<h3 class="anchored" data-anchor-id="songs-by-the-same-artist">3. Songs by the Same Artist</h3>
<p>Below is a list of Led Zeppelin or Creedence Clearwater Revival songs that match in sound and message.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 29 × 2
   name                                             artists                     
   &lt;chr&gt;                                            &lt;chr&gt;                       
 1 Kashmir - 1990 Remaster                          ['Led Zeppelin']            
 2 I Put A Spell On You                             ['Creedence Clearwater Revi…
 3 Whole Lotta Love - 1990 Remaster                 ['Led Zeppelin']            
 4 The Lemon Song - 1993 Remaster                   ['Led Zeppelin']            
 5 Going to California - 2012 Remaster              ['Led Zeppelin']            
 6 Down On The Corner                               ['Creedence Clearwater Revi…
 7 Up Around The Bend                               ['Creedence Clearwater Revi…
 8 Good Times Bad Times - 1993 Remaster             ['Led Zeppelin']            
 9 What Is and What Should Never Be - 1990 Remaster ['Led Zeppelin']            
10 The Wanton Song - 1990 Remaster                  ['Led Zeppelin']            
# ℹ 19 more rows</code></pre>
</div>
</div>
<hr>
</section>
<section id="songs-from-the-same-era-with-similar-sound" class="level3">
<h3 class="anchored" data-anchor-id="songs-from-the-same-era-with-similar-sound">4. Songs from the Same Era with Similar Sound</h3>
<p>These songs were released in the same time period and share similar acousticness, energy, and danceability values.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 6
   name                           artists  year acousticness danceability energy
   &lt;chr&gt;                          &lt;chr&gt;   &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;  &lt;dbl&gt;
 1 Loan Me a Dime                 ['Boz …  1969        0.309        0.392  0.471
 2 Ain't No Sunshine              ['Bill…  1971        0.457        0.479  0.416
 3 Contemplation                  ['McCo…  1967        0.48         0.397  0.534
 4 Goodbye Yellow Brick Road - R… ['Elto…  1973        0.446        0.559  0.473
 5 Somebody to Love               ['Jeff…  1967        0.408        0.504  0.578
 6 To Sir with Love               ['Lulu…  1967        0.361        0.546  0.399
 7 The Wind Cries Mary            ['Jimi…  1967        0.348        0.499  0.495
 8 Get Together                   ['The …  1967        0.467        0.542  0.492
 9 The Night They Drove Old Dixi… ['The …  1969        0.453        0.507  0.493
10 Me and Bobby McGee             ['Jani…  1971        0.302        0.453  0.464</code></pre>
</div>
</div>
<hr>
</section>
<section id="hidden-gems" class="level3">
<h3 class="anchored" data-anchor-id="hidden-gems">5. Hidden Gems</h3>
<p>These are songs that show up frequently in playlists but don’t have high popularity scores.</p>
<hr>
</section>
</section>
<section id="task-7-creating-the-ultimate-playlist" class="level2">
<h2 class="anchored" data-anchor-id="task-7-creating-the-ultimate-playlist">Task 7: Creating The Ultimate Playlist</h2>
<p>The time has arrived to construct the Ultimate Playlist from our identified candidate tracks.</p>
<p>This assignment requires both data analysis and creative judgment. Our two anchor songs <em>“Stairway to Heaven”</em> and <em>“Fortunate Son”</em> will serve as the base for constructing a 12-track playlist which maintains musical flow and thematic coherence while featuring established tracks alongside lesser-known songs.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Our playlist must meet the following criteria:</p>
<ul>
<li><p>at least <strong>12 tracks</strong>.</p></li>
<li><p><strong>2 songs that listeners have not heard before</strong>.</p></li>
<li><p><strong>3 songs that fail to meet our established popularity criteria</strong></p></li>
</ul>
</div>
</div>
<p>The playlist needs to demonstrate progression through its structure which can either ascend and descend or follow another pattern.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 71 × 2
   name                             artists         
   &lt;chr&gt;                            &lt;chr&gt;           
 1 Carry on Wayward Son             ['Kansas']      
 2 Brown Eyed Girl                  ['Van Morrison']
 3 Hotel California - 2013 Remaster ['Eagles']      
 4 More Than a Feeling              ['Boston']      
 5 Sweet Emotion                    ['Aerosmith']   
 6 Dream On                         ['Aerosmith']   
 7 House Of The Rising Sun          ['The Animals'] 
 8 Piano Man                        ['Billy Joel']  
 9 Thunderstruck                    ['AC/DC']       
10 American Pie                     ['Don McLean']  
# ℹ 61 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="mp03_files/figure-html/playlist-energy-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="the-ultimate-playlist-rock-vinyl-classics" class="level2">
<h2 class="anchored" data-anchor-id="the-ultimate-playlist-rock-vinyl-classics">The Ultimate Playlist: <em>Rock Vinyl Classics</em></h2>
<p>The playlist follows a chronologicalpath through rock music history by combining powerful guitar solos with meaningful lyrics and everlasting musical compositions.</p>
<section id="description" class="level3">
<h3 class="anchored" data-anchor-id="description">📝 Description</h3>
<p>The playlist begins with emotional masterpieces which transform into an intense storm before ending with peaceful music. The playlist unites well-known songs with lesser-known tracks to create musical unity througdifferent energetic and tonal and instrumental elements.</p>
</section>
<section id="design-principles" class="level3">
<h3 class="anchored" data-anchor-id="design-principles">🎧 Design Principles</h3>
<p>The emotional foundation of the playlist begins with “Stairway to Heaven” and “Fortunate Son.”</p>
<p>The song arrangement follows a dynamic pattern which alternates between powerful sections and contemplative moments.</p>
<p>The playlist features a visual representation of acoustic elements and tempo and energy levels to achieve balanced peaks and valleys.</p>
<p>The playlist contains at least two unknown tracks and three lesser-known songs which demonstrate that exceptional music does not need widespread popularity.</p>
<p>The playlist weaves a narrative that explores both the musical genre and the historical period.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>